//! web/pages — Halaman aplikasi (SSR + hydrate).

mod akademik;
mod analisis;
mod artikel;
mod artikel_kelola;
// `pub`: halaman artikel memakai bilah nav & kaki halaman publiknya.
pub mod beranda;
mod dashboard_santri;
mod design_pages;
mod tamu_masuk;
mod galeri;
mod ganti_sandi;
mod izin;
mod izin_aktif;
mod izin_staf;
mod kalender;
mod kelas;
mod kelas_detail;
mod kelas_saya;
mod kontrol_pengguna;
mod laporan;
mod login;
mod manajemen_user;
mod materi;
mod menu;
mod not_found;
mod ortu_beranda;
mod ortu_izin;
mod ortu_pembayaran;
mod ortu_riwayat;
mod poin;
mod profil;
mod register;
mod rekap;
mod riwayat;
mod server_status;
mod sesi;
mod sesi_detail;
mod sesi_live;
mod staf;
mod students;
// `pub`: halaman pembayaran orang tua memakai form pengajuan & daftar
// riwayatnya — satu komponen untuk kedua layar (lihat ortu_pembayaran.rs).
pub mod tagihan;
mod tamu;
mod verifikasi_tahap2;

pub use akademik::AkademikSantriPage;
pub use analisis::{DewanGuruDashboardPage, GuruDashboardPage};
pub use artikel::{ArtikelDetailPage, ArtikelListPage};
pub use artikel_kelola::KelolaArtikelPage;
pub use kelas_saya::KelasSayaPage;
pub use beranda::BerandaPage;
pub use dashboard_santri::SantriDashboardPage;
pub use design_pages::*;
pub use tamu_masuk::*;
pub use galeri::GaleriPage;
pub use ganti_sandi::GantiSandiPage;
pub use izin::IzinPage;
pub use izin_aktif::IzinAktifPage;
pub use izin_staf::IzinStafPage;
pub use kalender::KalenderPage;
pub use kelas::KelasPage;
pub use kelas_detail::{KelasDetailPage, KurikulumTab, PosisiBerjalan};
pub use kontrol_pengguna::KontrolPenggunaPage;
pub use laporan::LaporanPage;
pub use login::LoginPage;
pub use manajemen_user::ManajemenUserPage;
pub use materi::{MaterialsWidget, MateriPage};
pub use menu::MenuPage;
pub use not_found::NotFoundPage;
pub use ortu_beranda::OrtuBerandaPage;
pub use ortu_izin::OrtuIzinPage;
pub use ortu_pembayaran::OrtuPembayaranPage;
pub use ortu_riwayat::OrtuRiwayatPage;
pub use poin::{PoinDetailPage, PoinPage, PoinSayaPage};
pub use profil::ProfilPage;
pub use register::RegisterPage;
pub use rekap::RekapMingguanPage;
pub use riwayat::RiwayatPage;
pub use server_status::StatusServerPage;
pub use sesi::{SesiContent, SesiPage};
pub use sesi_detail::SesiDetailPage;
pub use sesi_live::SesiLivePage;
pub use students::{StudentBookPanel, StudentsPage};
pub use staf::StafDashboardPage;
pub use tagihan::{FinancePage, MyBillsPage};
pub use tamu::TamuPage;
pub use verifikasi_tahap2::VerifikasiTahap2Page;
